#! /bin/bash
if [[ ${UID} -ne 0 ]]
then
echo "u need root privilages to proceed" 1>&2
exit 1
fi
if [[ $# -eq 0 ]]
then
echo 'u have to enter username and comments(if required)' 1>&2
echo 'enter it in the following format: # /.newusers <username> <comments>' 1>&2
exit 1
fi
USERNAME=$1
PASSWORD=$(echo date +%s%N${RANDOM} | sha256sum | shuf | head -c10 )

if [[ $# -gt 1 ]]
then 
shift
COMMENT=$*
fi

useradd -c "$COMMENTS" -m $USERNAME > /dev/null
if [[ ${?} -ne 0 ]]
then
echo 'user could not be created'
fi
echo $PASSWORD |passwd --stdin $USERNAME > /dev/null 
passwd -e $USERNAME > /dev/null

echo
echo "username: $USERNAME"
echo "password: $PASSWORD"
echo "hostname: ${HOSTNAME}"
if [[ $# -gt 1 ]]
then
echo "comments: $COMMENT"
fi

