#! /bin/bash
if [[ ${UID} -ne 0 ]]
then 
echo "u need to be the root user to run this application"
exit 1
fi
read -p 'enter the username to be added: ' USERNAME 
read -p 'enter ur name:' COMMENTS 
read -p 'enter ur password:' PASSWORD 
useradd -c "${COMMENTS}" -m ${USERNAME} 
echo ${PASSWORD} | passwd --stdin ${USERNAME} 
passwd -e ${USERNAME}
echo "user name: ${USERNAME}"
echo "password: ${PASSWORD}"

